init:
  - git config --global core.autocrlf true

environment:
    MSVS_VERSION: 2013

    matrix:
        - nodejs_version: "4.2"
        - nodejs_version: "4.4"
        - nodejs_version: "5.1"
        - nodejs_version: "5.4"

platform:
    - x86
    - x64

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install --msvs_version=%MSVS_VERSION%

test_script:
    - node --version
    - npm --version
    - cmd: npm test

build: off
